### ISSUE TITLE
Start to update dependencies. Review dependabot requests

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/alphagpo#31]
It might be time to start reviewing the automated pull requests from dependabot and update this project's dependencies. Most of the other problems with this project have been dealt with so there is time to check package upgrades and make sure the project does not break. For the time being, mygpo will definitely still target Django 3.x rather than attempting to upgrade to Django 4.x.

**Comment by 10leej** [comment]
there a public instance running this fork yet? or should I look to self host

**Comment by Ryochan7** [comment]
A public instance has been available since about mid January. Should probably update the repo info with the URL.

https://alphagpo.ryochan7.org/
